<?php

/**
 * Electoral districts of Law 44/2017 Annex 1: 15 major districts (دوائر كبرى) and 26 minor districts
 * (دوائر صغرى). Keys are the values stored in positions.seat_major_district / seat_minor_district;
 * the graph exporter attaches the names to seat nodes. 'expatriates' covers the Art. 112 seats.
 */
return [
    'major' => [
        'beirut-1' => ['ar' => 'بيروت الأولى', 'en' => 'Beirut I', 'fr' => 'Beyrouth I'],
        'beirut-2' => ['ar' => 'بيروت الثانية', 'en' => 'Beirut II', 'fr' => 'Beyrouth II'],
        'south-1' => ['ar' => 'الجنوب الأولى', 'en' => 'South I', 'fr' => 'Sud I'],
        'south-2' => ['ar' => 'الجنوب الثانية', 'en' => 'South II', 'fr' => 'Sud II'],
        'south-3' => ['ar' => 'الجنوب الثالثة', 'en' => 'South III', 'fr' => 'Sud III'],
        'bekaa-1' => ['ar' => 'البقاع الأولى', 'en' => 'Bekaa I', 'fr' => 'Békaa I'],
        'bekaa-2' => ['ar' => 'البقاع الثانية', 'en' => 'Bekaa II', 'fr' => 'Békaa II'],
        'bekaa-3' => ['ar' => 'البقاع الثالثة', 'en' => 'Bekaa III', 'fr' => 'Békaa III'],
        'north-1' => ['ar' => 'الشمال الأولى', 'en' => 'North I', 'fr' => 'Nord I'],
        'north-2' => ['ar' => 'الشمال الثانية', 'en' => 'North II', 'fr' => 'Nord II'],
        'north-3' => ['ar' => 'الشمال الثالثة', 'en' => 'North III', 'fr' => 'Nord III'],
        'mount-lebanon-1' => ['ar' => 'جبل لبنان الأولى', 'en' => 'Mount Lebanon I', 'fr' => 'Mont-Liban I'],
        'mount-lebanon-2' => ['ar' => 'جبل لبنان الثانية', 'en' => 'Mount Lebanon II', 'fr' => 'Mont-Liban II'],
        'mount-lebanon-3' => ['ar' => 'جبل لبنان الثالثة', 'en' => 'Mount Lebanon III', 'fr' => 'Mont-Liban III'],
        'mount-lebanon-4' => ['ar' => 'جبل لبنان الرابعة', 'en' => 'Mount Lebanon IV', 'fr' => 'Mont-Liban IV'],
        'expatriates' => ['ar' => 'المنتشرون', 'en' => 'Expatriates', 'fr' => 'Émigrés'],
    ],
    'minor' => [
        'beirut-1' => ['ar' => 'بيروت الأولى', 'en' => 'Beirut I', 'fr' => 'Beyrouth I'],
        'beirut-2' => ['ar' => 'بيروت الثانية', 'en' => 'Beirut II', 'fr' => 'Beyrouth II'],
        'saida' => ['ar' => 'صيدا', 'en' => 'Saida', 'fr' => 'Saïda'],
        'jezzine' => ['ar' => 'جزين', 'en' => 'Jezzine', 'fr' => 'Jezzine'],
        'tyre' => ['ar' => 'صور', 'en' => 'Tyre', 'fr' => 'Tyr'],
        'zahrani' => ['ar' => 'الزهراني', 'en' => 'Zahrani', 'fr' => 'Zahrani'],
        'bint-jbeil' => ['ar' => 'بنت جبيل', 'en' => 'Bint Jbeil', 'fr' => 'Bint Jbeil'],
        'nabatieh' => ['ar' => 'النبطية', 'en' => 'Nabatieh', 'fr' => 'Nabatiyeh'],
        'marjeyoun-hasbaya' => ['ar' => 'مرجعيون – حاصبيا', 'en' => 'Marjeyoun–Hasbaya', 'fr' => 'Marjeyoun–Hasbaya'],
        'zahle' => ['ar' => 'زحلة', 'en' => 'Zahle', 'fr' => 'Zahlé'],
        'west-bekaa-rashaya' => ['ar' => 'البقاع الغربي – راشيا', 'en' => 'West Bekaa–Rashaya', 'fr' => 'Békaa-Ouest–Rachaya'],
        'baalbek-hermel' => ['ar' => 'بعلبك – الهرمل', 'en' => 'Baalbek–Hermel', 'fr' => 'Baalbek–Hermel'],
        'akkar' => ['ar' => 'عكار', 'en' => 'Akkar', 'fr' => 'Akkar'],
        'tripoli' => ['ar' => 'طرابلس', 'en' => 'Tripoli', 'fr' => 'Tripoli'],
        'minieh' => ['ar' => 'المنية', 'en' => 'Minieh', 'fr' => 'Minié'],
        'denniyeh' => ['ar' => 'الضنية', 'en' => 'Denniyeh', 'fr' => 'Denniyé'],
        'zgharta' => ['ar' => 'زغرتا', 'en' => 'Zgharta', 'fr' => 'Zghorta'],
        'bcharre' => ['ar' => 'بشري', 'en' => 'Bcharre', 'fr' => 'Bcharré'],
        'koura' => ['ar' => 'الكورة', 'en' => 'Koura', 'fr' => 'Koura'],
        'batroun' => ['ar' => 'البترون', 'en' => 'Batroun', 'fr' => 'Batroun'],
        'jbeil' => ['ar' => 'جبيل', 'en' => 'Jbeil', 'fr' => 'Jbeil'],
        'keserwan' => ['ar' => 'كسروان', 'en' => 'Keserwan', 'fr' => 'Kesrouan'],
        'metn' => ['ar' => 'المتن', 'en' => 'Metn', 'fr' => 'Metn'],
        'baabda' => ['ar' => 'بعبدا', 'en' => 'Baabda', 'fr' => 'Baabda'],
        'chouf' => ['ar' => 'الشوف', 'en' => 'Chouf', 'fr' => 'Chouf'],
        'aley' => ['ar' => 'عاليه', 'en' => 'Aley', 'fr' => 'Aley'],
    ],
    'minorToMajor' => [
        'beirut-1' => 'beirut-1',
        'beirut-2' => 'beirut-2',
        'akkar' => 'north-1',
        'minieh' => 'north-2',
        'denniyeh' => 'north-2',
        'tripoli' => 'north-2',
        'zgharta' => 'north-3',
        'koura' => 'north-3',
        'bcharre' => 'north-3',
        'batroun' => 'north-3',
        'jbeil' => 'mount-lebanon-1',
        'keserwan' => 'mount-lebanon-1',
        'metn' => 'mount-lebanon-2',
        'baabda' => 'mount-lebanon-3',
        'aley' => 'mount-lebanon-4',
        'chouf' => 'mount-lebanon-4',
        'saida' => 'south-1',
        'jezzine' => 'south-1',
        'zahrani' => 'south-2',
        'tyre' => 'south-2',
        'nabatieh' => 'south-3',
        'marjeyoun-hasbaya' => 'south-3',
        'bint-jbeil' => 'south-3',
        'zahle' => 'bekaa-1',
        'west-bekaa-rashaya' => 'bekaa-2',
        'baalbek-hermel' => 'bekaa-3',
    ],
];
